### ISSUE TITLE
Demo opzet

### ISSUE THREAD

**Issue by sgort** [discipl/Waardewisselaar#2]
Op demo platform een simpele uitwerking maken middels een munt voor het inkopen van educatie. Deze demo en een korte schets van de applicatie zoals we die voor ogen hebben kan worden getoond bij een terugkoppeling aan het Kernteam Bestuur

**Comment by milovanderlinden** [comment]
Gelijkwaardig aan realisatie prototype. Ik heb prototype gemigreerd naar een milestone. Op die manier kun je oplevermomenten uitzetten en per oplevering de werk-items groeperen.
