### ISSUE TITLE
Concept WW rapportage - staccato inhoud vullen

### ISSUE THREAD

**Issue by chantalvdwijst** [discipl/Waardewisselaar#44]
[Rapportage Concept Waardewisselaar - opzet hoofdstukken.docx](https://github.com/discipl/Waardewisselaar/files/2209874/Rapportage.Concept.Waardewisselaar.-.opzet.hoofdstukken.docx)
Deelnemers van de pilot en met name de leden kerngroep Bestuur leveren bijdragen in de inhoud.

**Comment by pdepagter** [comment]
[Rapportage.Concept.Waardewisselaar.-.opzet.hoofdstukken.docx](https://github.com/discipl/Waardewisselaar/files/2249698/Rapportage.Concept.Waardewisselaar.-.opzet.hoofdstukken.docx)
Inhoud van de rapportage aangevuld met onderwerpen en inhoud.

**Comment by wietsinno** [comment]
enkele toevoegingen die mij nog te binnen schoten. 
[Rapportage.Concept.Waardewisselaar.-.opzet.hoofdstukken (1)_WE.docx](https://github.com/discipl/Waardewisselaar/files/2301770/Rapportage.Concept.Waardewisselaar.-.opzet.hoofdstukken.1._WE.docx)
