### ISSUE TITLE
Usecase 1 - B003.BR04 fout in logica

### ISSUE THREAD

**Issue by ewnbis** [discipl/Waardewisselaar#48]
De logica van B002.BR04 klopt niet naar ons idee. Er staat dat een leraar aan beide voorwaarden moet voldoen, dat is een gekke combinatie van voorwaarden. Deze sectie is ontleent aan wetsartikel 3.4:

Lid 4: In afwijking van het derde lid kan subsidie worden verstrekt voor een tweede opleiding indien:
a. subsidie wordt aangevraagd voor een masteropleiding en reeds subsidie is ontvangen voor een bacheloropleiding;
b. subsidie wordt aangevraagd voor een masteropleiding en reeds subsidie is ontvangen voor een deficiëntieopleiding, met dien verstande dat indien reeds subsidie voor het volgen van een deficiëntieopleiding is verleend, voor een opleiding van meer dan 60 studiepunten ten hoogste twee maal subsidie wordt verleend; **en**
c. subsidie is ontvangen op basis van de Regeling lerarenbeurs voor scholing, zij-instroom en bewegingsonderwijs 2009–2017 zoals deze gold vóór 1 april 2013 voor een opleiding anders dan een deficiëntie-, bachelor- of masteropleiding.

Volgens ons moet de logica In B002.BR04 zijn dat aan minstens één van deze voorwaarden voldaan moet worden.

**Comment by CeesJeeVee** [comment]
Je moet of een deficientie of een bachelor hebben gedaan om ondanks eerdere subsidie toch voor een nieuwe subsidie voor een  master-opleiding in aanmerking te komen

**Comment by ewnbis** [comment]
Dat begreep ik ook. Dan moet het in BR04 toch niet zijn dat je aan beide voorwaarden voldaan moet hebben?
(Excuses, ik zag dat ik naar het verkeerde document verwees, heb de titel aangepast)

**Comment by Stijn74** [comment]
[20180801 v1.2 B003 Aantal keer aangevraagd.pdf](https://github.com/discipl/Waardewisselaar/files/2248767/20180801.v1.2.B003.Aantal.keer.aangevraagd.pdf)
[20180801 v1.2 B003 Diagram Aantal keer aangevraagd.pdf](https://github.com/discipl/Waardewisselaar/files/2248768/20180801.v1.2.B003.Diagram.Aantal.keer.aangevraagd.pdf)
'en' vervangen door 'of'
