### ISSUE TITLE
Usecase 1 - B003.BR08 Welke master mag je kiezen?

### ISSUE THREAD

**Issue by ewnbis** [discipl/Waardewisselaar#49]
Moet er op de blockchain worden bijgehouden welke masteropleiding volgt op een bachelor- of deficiëntieopleiding? Of mag een leraar elke masteropleiding kiezen? 

Kortom: hoe weten we of een masteropleiding volgt op een voorgaande opleiding?

**Comment by CeesJeeVee** [comment]
Je kunt er vanuit gaan dat bekend is welke bachelor op welke master volgt. DUO heeft die gegevens.
De master moet inderdaad wel horen bij de bachelor. De deficientieopleiding moet ook horen bij de master want die doe je juist om vervolgens de master te kunnen doen

**Comment by ewnbis** [comment]
Als we de toekenning volledig willen automatiseren op de blockchain moet deze informatie dus ook bekend zijn op de blockchain, of we nemen deze informatie niet mee en baseren daar dus ook de toekenning niet op. Wat heeft jullie voorkeur?

**Comment by ewnbis** [comment]
Technisch overleg 30 juli: Conclusie: welke master volgt op welke bachelor- of deficiëntie opleiding laten we buiten scope. 
Het aanmaken van een nieuwe opleiding is wel mogelijk.
