### ISSUE TITLE
Usecase 1 - B003.BR08.4 t/m BR10: niet relevant voor pilot?

### ISSUE THREAD

**Issue by ewnbis** [discipl/Waardewisselaar#50]
Wij stellen voor deze bepalingen over hoe we om moeten gaan met oude regelingen niet mee te nemen. Dit weten we namelijk niet. DUO zou dan van elke docent de volledige subsidiehistorie toe moeten voegen op de blockchain. Dat lijkt ons niet haalbaar voor een pilot.

**Comment by CeesJeeVee** [comment]
Lijkt mij voor de pilot prima

**Comment by ewnbis** [comment]
Technisch overleg 30 juli: eens met conclusie CeeJeeVee
