### ISSUE TITLE
Usecase 1 - B002.BR02 en BR04: Is er verschil?

### ISSUE THREAD

**Issue by ewnbis** [discipl/Waardewisselaar#51]
Wat is het verschil tussen BR02 en BR04? De consequentie voor de blockchain lijken ons in ieder geval gelijk.

**Comment by CeesJeeVee** [comment]
Er is wel verschil, maar denk niet relevant voor nu

**Comment by ewnbis** [comment]
Technisch overleg 30 juli: BR04 is recente werkzaamheden, al dan niet met dienstverband. BR02 gaat alleen over dienstverband. Dus je moet zowel zo aan recente werkzaamheden als aan een dienstverband voldoen. 
Conclusie: we nemen in de pilot alleen mee dat een leraar onderwijs moet hebben gegeven op een school, dienstverband (BR02) checken we niet apart.
